/// <reference types="vite/client" />

declare const __SEARCH_FORMULATION_MODEL__: string;
declare const __OLLAMA_FALLBACK_MODEL__: string;
declare const __OLLAMA_DEEP_ANSWER_MODEL__: string;
declare const __PRIOR_ASSISTANT_BUDGET_CHARS__: number;
declare const __PRIOR_ASSISTANT_BUDGET_CHARS_DEEP__: number;
declare const __OLLAMA_ANSWER_NUM_CTX__: number;
declare const __OLLAMA_DEEP_ANSWER_NUM_CTX__: number;
declare const __OLLAMA_JSON_NUM_CTX__: number;
declare const __GAP_FOLLOW_UP_MAX__: number;
declare const __SEARCH_FORMULATION_PRIOR_BUDGET_CHARS__: number;
declare const __SEARCH_FORMULATION_NUM_CTX__: number;
declare const __ARCHON_SHALLOW_PER_QUERY__: number;
declare const __ARCHON_SHALLOW_MAX_TOTAL__: number;
declare const __ARCHON_SHALLOW_MAX_ROUNDS__: number;
declare const __ARCHON_DEEP_PER_QUERY__: number;
declare const __ARCHON_DEEP_MAX_TOTAL__: number;
declare const __ARCHON_DEEP_MAX_ROUNDS__: number;
declare const __ARCHON_EXTRACT_MAX_URLS__: number;
